%YAML:1.0

BaseConfig:
  minDetectorConfidence: 0.1      # Don't drop boxes the AI is unsure about
  maxTargetsPerStream: 20         # Max faces to track at once
  # These must match your PGIE inference dimensions
  trackerWidth: 640               
  trackerHeight: 640
  gpuId: 0

IOUTracker:
  # The IOU tracker is great for Nano because it uses very little GPU
  iouThreshold: 0.2               # Lower this to make tracking "stickier"
  minConsecutiveFrames: 1         # Show the box IMMEDIATELY (don't wait)
  maxWaitFramesForSpatioTemporalConfidence: 3